classdef prjDirStruct < handle
    %prjDirStruct Define the paths of the project folder structure
    %
    %   prjDirStruct.dirKeys returns all available keys for identifying
    %   folder paths.
    %
    %   prjDirStruct.getDirPath(key) returns the folder path identified by
    %   the given key.
    %
    %   prjDirStruct.getDirPath(key, model) returns the folder path
    %   identified by the given key for the specified model.
    
    properties (Constant)
        prj = currentProject();
        rootDir = char(prjDirStruct.prj.RootFolder);
        
        %************************** CUSTOMIZABLE **************************%
        % NOTE: Use the token <MODEL> to insert model name in the path. It %
        % will be automatically replaced by the actual model name when you %
        % provide the name as an argument to the getDirPath method.        %
        %******************************************************************%
        dirKeys = {'root'; ...
                   'checklists'; ...
                   'plans'; ...
                   'standards'; ...
                   'requirements root'; ...
                   'requirements specification'; ...
                   'requirements review'; ...
                   'architecture root'; ...
                   'architecture analysis'; ...
                   'architecture specification'; ...
                   'architecture review'; ...
                   'design root'; ...
                   'block libraries'; ...
                   'shared data'; ...
                   'shared types'; ...
                   'model root'; ...
                   'model'; ...
                   'model data'; ...
                   'SDD report'; ...
                   'test cases'; ...
                   'HLR test cases'; ...
                   'LLR test cases'; ...
                   'BV test cases'; ...
                   'model verification'; ...
                   'design error detection'; ...
                   'dead logic analysis'; ...
                   'design error analysis'; ...
                   'model standards'; ...
                   'model coverage'; ...
                   'HLR model coverage'; ...
                   'LLR model coverage'; ...
                   'BV model coverage'; ...
                   'model metrics'; ...
                   'model review'; ...
                   'model gate review'; ...
                   'verification gate review'; ...
                   'sim results'; ...
                   'HLR sim results'; ...
                   'LLR sim results'; ...
                   'BV sim results'; ...
                   'code root'; ...
                   'code'; ...
                   'top model code'; ...
                   'ref model code'; ...
                   'code verification'; ...
                   'code coverage root'; ...
                   'code coverage'; ...
                   'SIL coverage'; ...
                   'HLR SIL coverage'; ...
                   'LLR SIL coverage'; ...
                   'BV SIL coverage'; ...
                   'PIL coverage'; ...
                   'HLR PIL coverage'; ...
                   'LLR PIL coverage'; ...
                   'BV PIL coverage'; ...
                   'code metrics root'; ...
                   'code metrics'; ...
                   'code prover root'; ...
                   'code prover'; ...
                   'code review root'; ...
                   'code review'; ...
                   'code standards root'; ...
                   'code standards'; ...
                   'bug finder root'; ...
                   'bug finder'; ...
                   'test results root'; ...
                   'test results'; ...
                   'SIL results'; ...
                   'HLR SIL results'; ...
                   'LLR SIL results'; ...
                   'BV SIL results'; ...
                   'PIL results'; ...
                   'HLR PIL results'; ...
                   'LLR PIL results'; ...
                   'BV PIL results'; ...
                   'tool qual root'; ...
                   'help'; ...
                   'tools'; ...
                   'work'; ...
                   'xil'; ...
                   'sil'; ...
                   'pil'; ...
                   'project configuration root'};
        dirVals = {fullfile(prjDirStruct.rootDir); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_01_Planning', 'checklists'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_01_Planning', 'plans'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_01_Planning', 'standards'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_02_Requirements'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_02_Requirements', 'specification'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_02_Requirements', 'verification_results'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_03_Architecture'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_03_Architecture', 'analysis'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_03_Architecture', 'specification'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_03_Architecture', 'verification_results'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_04_Design'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_04_Design', 'common', 'specification', 'block_libraries'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_04_Design', 'common', 'specification', 'data'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_04_Design', 'common', 'specification', 'data_types'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_04_Design', '<MODEL>'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_04_Design', '<MODEL>', 'specification'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_04_Design', '<MODEL>', 'specification', 'data'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_04_Design', '<MODEL>', 'specification', 'documents'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_04_Design', '<MODEL>', 'test_cases'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_04_Design', '<MODEL>', 'test_cases', 'RBT'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_04_Design', '<MODEL>', 'test_cases', 'SBT'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_04_Design', '<MODEL>', 'test_cases', 'BV'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_04_Design', '<MODEL>', 'verification_results'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_04_Design', '<MODEL>', 'verification_results', 'design_error_detections'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_04_Design', '<MODEL>', 'verification_results', 'design_error_detections', 'dead_logic'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_04_Design', '<MODEL>', 'verification_results', 'design_error_detections', 'design_error'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_04_Design', '<MODEL>', 'verification_results', 'design_standard_checks'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_04_Design', '<MODEL>', 'verification_results', 'model_coverages'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_04_Design', '<MODEL>', 'verification_results', 'model_coverages', 'RBT'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_04_Design', '<MODEL>', 'verification_results', 'model_coverages', 'SBT'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_04_Design', '<MODEL>', 'verification_results', 'model_coverages', 'BV'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_04_Design', '<MODEL>', 'verification_results', 'model_metrics'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_04_Design', '<MODEL>', 'verification_results', 'model_reviews'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_04_Design', '<MODEL>', 'verification_results', 'model_gate_reviews'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_04_Design', '<MODEL>', 'verification_results', 'verification_reviews'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_04_Design', '<MODEL>', 'verification_results', 'simulation_results'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_04_Design', '<MODEL>', 'verification_results', 'simulation_results', 'RBT'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_04_Design', '<MODEL>', 'verification_results', 'simulation_results', 'SBT'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_04_Design', '<MODEL>', 'verification_results', 'simulation_results', 'BV'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_05_Code'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_05_Code', 'specification'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_05_Code', 'specification', '<MODEL>_ert_rtw'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_05_Code', 'specification', 'slprj', 'ert', '<MODEL>'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_05_Code', 'verification_results'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_05_Code', 'verification_results', 'code_coverages'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_05_Code', 'verification_results', 'code_coverages', '<MODEL>'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_05_Code', 'verification_results', 'code_coverages', '<MODEL>', 'host'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_05_Code', 'verification_results', 'code_coverages', '<MODEL>', 'host', 'RBT'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_05_Code', 'verification_results', 'code_coverages', '<MODEL>', 'host', 'SBT'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_05_Code', 'verification_results', 'code_coverages', '<MODEL>', 'host', 'BV'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_05_Code', 'verification_results', 'code_coverages', '<MODEL>', 'target'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_05_Code', 'verification_results', 'code_coverages', '<MODEL>', 'target', 'RBT'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_05_Code', 'verification_results', 'code_coverages', '<MODEL>', 'target', 'SBT'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_05_Code', 'verification_results', 'code_coverages', '<MODEL>', 'target', 'BV'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_05_Code', 'verification_results', 'code_metrics'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_05_Code', 'verification_results', 'code_metrics', '<MODEL>'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_05_Code', 'verification_results', 'code_proving'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_05_Code', 'verification_results', 'code_proving', '<MODEL>'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_05_Code', 'verification_results', 'code_reviews'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_05_Code', 'verification_results', 'code_reviews', '<MODEL>'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_05_Code', 'verification_results', 'code_standard_checks'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_05_Code', 'verification_results', 'code_standard_checks', '<MODEL>'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_05_Code', 'verification_results', 'coding_error_detections'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_05_Code', 'verification_results', 'coding_error_detections', '<MODEL>'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_05_Code', 'verification_results', 'eoc_test_results'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_05_Code', 'verification_results', 'eoc_test_results', '<MODEL>'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_05_Code', 'verification_results', 'eoc_test_results', '<MODEL>', 'host'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_05_Code', 'verification_results', 'eoc_test_results', '<MODEL>', 'host', 'RBT'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_05_Code', 'verification_results', 'eoc_test_results', '<MODEL>', 'host', 'SBT'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_05_Code', 'verification_results', 'eoc_test_results', '<MODEL>', 'host', 'BV'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_05_Code', 'verification_results', 'eoc_test_results', '<MODEL>', 'target'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_05_Code', 'verification_results', 'eoc_test_results', '<MODEL>', 'target', 'RBT'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_05_Code', 'verification_results', 'eoc_test_results', '<MODEL>', 'target', 'SBT'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_05_Code', 'verification_results', 'eoc_test_results', '<MODEL>', 'target', 'BV'); ...
                   fullfile(prjDirStruct.rootDir, 'ISO_06_ToolQualification'); ...
                   fullfile(prjDirStruct.rootDir, 'help'); ...
                   fullfile(prjDirStruct.rootDir, 'tools'); ...
                   fullfile(prjDirStruct.rootDir, 'work'); ...
                   fullfile(prjDirStruct.rootDir, 'work', 'xil', '<MODEL>'); ...
                   fullfile(prjDirStruct.rootDir, 'work', 'sil', '<MODEL>'); ...
                   fullfile(prjDirStruct.rootDir, 'work', 'pil', '<MODEL>'); ...
                   fullfile(prjDirStruct.rootDir, 'project_configuration')};
        dirMap = containers.Map(prjDirStruct.dirKeys, prjDirStruct.dirVals);
    end
    
    methods (Static)
        function dirPath = getDirPath(key, varargin)
            if nargin > 1
                dirPath = prjDirStruct.dirMap(key);
                dirPath = strrep(dirPath, '<MODEL>', varargin{1});
            else
                dirPath = prjDirStruct.dirMap(key);
            end
        end
    end
    
end
