classdef prjNameConv < handle
    %prjNameConv Define the names of all artifacts stored in the project
    %
    %   prjNameConv.nameKeys returns all available keys for identifying
    %   artifact names.
    %
    %   prjNameConv.getNameStr(key) returns the artifact name identified by
    %   the given key.
    %
    %   prjNameConv.getNameStr(key, model) returns the artifact name
    %   identified by the given key for the specified model.
    
    properties (Constant)
        %************************** CUSTOMIZABLE **************************%
        % NOTE: Use the token <MODEL> to insert model name in the name. It %
        % will be automatically replaced by the actual model name when you %
        % provide the name as an argument to the getNameStr method.        %
        %******************************************************************%
        
                                                          %================================================================================ %
                                                          % DESCRIPTION                                       | CREATED BY                  %
                                                          %=================================================================================%
        nameKeys = {'load command'; ...                   % Model load/open script                            | addModelFolder              %
                    'model data'; ...                     % Model data dictionary                             | addModelFolder              %
                    'local model data'; ...               % Local model data file                             | addModelFolder              %
                    'requirements report'; ...            % Requirements report                               | genReqReport                %
                    'SDD report'; ...                     % System design description report                  | genSDD                      %
                    'HLR test harness'; ...               % Requirement-based test harness                    |                             %
                    'HLR test cases';                     % Requirement-based test cases                      |                             %
                    'HLR sim results'; ...                % Requirement-based simulation test results         | verifyModel2Reqs            %
                    'HLR sim report'; ...                 % Requirement-based simulation test report          | verifyModel2Reqs            %
                    'HLR model coverage'; ...             % Requirement-based model coverage results          | verifyModel2Reqs            %
                    'HLR model coverage report'; ...      % Requirement-based model coverage report           | verifyModel2Reqs            %
                    'test generation report';             % Test generation report                            | genLowLevelTests            %
                    'LLR test harness'; ...               % Structure-based test harness                      | genLowLevelTests            %
                    'LLR test cases'; ...                 % Structure-based test cases                        | genLowLevelTests            %
                    'LLR sim results'; ...                % Structure-based simulation test results           | verifyModel2LowLevelTests   %
                    'LLR sim report'; ...                 % Structure-based simulation test report            | verifyModel2LowLevelTests   %
                    'LLR model coverage'; ...             % Structure-based model coverage results            | verifyModel2LowLevelTests   %
                    'LLR model coverage report'; ...      % Structure-based model coverage report             | verifyModel2LowLevelTests   %
                    'BV test generation report';          % Boundary value Test generation report             | genBoundValTests            %
                    'BV test harness'; ...                % Boundary value test harness                       | genBoundValTests            %
                    'BV test cases'; ...                  % Boundary value test cases                         | genBoundValTests            %
                    'BV sim results'; ...                 % Boundary value simulation test results            | verifyModel2BoundValTests   %
                    'BV sim report'; ...                  % Boundary value simulation test report             | verifyModel2BoundValTests   %
                    'BV model coverage'; ...              % Boundary value model coverage results             | verifyModel2BoundValTests   %
                    'BV model coverage report'; ...       % Boundary value model coverage report              | verifyModel2BoundValTests   %
                    'model coverage'; ...                 % Cumulative model coverage results                 | mergeModelCoverage          %
                    'model coverage report'; ...          % Cumulative model coverage report                  | mergeModelCoverage          %
                    'model standards report'; ...         % Modeling rules analysis repor                     | checkModelStds              %
                    'model metrics report'; ...           % Model metrics analysis report                     | computeModelMetrics         %
                    'design error detection results'; ... % Design error analysis (DED) results               | detectDesignErrs            %
                    'design error detection report'; ...  % Design error analysis (DED) report                | detectDesignErrs            %
                    'HLR SIL results'; ...                % Requirement-based SIL test results                | verifyObjCode2Reqs          %
                    'HLR SIL report'; ...                 % Requirement-based SIL test report                 | verifyObjCode2Reqs          %
                    'HLR PIL results'; ...                % Requirement-based PIL test results                | verifyObjCode2Reqs          %
                    'HLR PIL report'; ...                 % Requirement-based PIL test report                 | verifyObjCode2Reqs          %
%                     'HLR SIL results (instrumented)'; ... % Requirement-based SIL test results (instrumented) | verifyObjCode2Reqs          %
%                     'HLR SIL report (instrumented)'; ...  % Requirement-based SIL test report (instrumented)  | verifyObjCode2Reqs          %
%                     'HLR PIL results (instrumented)'; ... % Requirement-based PIL test results (instrumented) | verifyObjCode2Reqs          %
%                     'HLR PIL report (instrumented)'; ...  % Requirement-based PIL test report (instrumented)  | verifyObjCode2Reqs          %
                    'HLR code coverage'; ...              % Requirement-based code coverage results           | verifyObjCode2Reqs          %
                    'HLR code coverage report'; ...       % Requirement-based code coverage report            | verifyObjCode2Reqs          %
                    'LLR SIL results'; ...                % Structure-based SIL test results                  | verifyObjCode2LowLevelTests %
                    'LLR SIL report'; ...                 % Structure-based SIL test report                   | verifyObjCode2LowLevelTests %
                    'LLR PIL results'; ...                % Structure-based PIL test results                  | verifyObjCode2LowLevelTests %
                    'LLR PIL report'; ...                 % Structure-based PIL test report                   | verifyObjCode2LowLevelTests %
%                     'LLR SIL results (instrumented)'; ... % Structure-based SIL test results (instrumented)   | verifyObjCode2LowLevelTests %
%                     'LLR SIL report (instrumented)'; ...  % Structure-based SIL test report (instrumented)    | verifyObjCode2LowLevelTests %
%                     'LLR PIL results (instrumented)'; ... % Structure-based PIL test results (instrumented)   | verifyObjCode2LowLevelTests %
%                     'LLR PIL report (instrumented)'; ...  % Structure-based PIL test report (instrumented)    | verifyObjCode2LowLevelTests %
                    'LLR code coverage'; ...              % Structure-based code coverage results             | verifyObjCode2LowLevelTests %
                    'LLR code coverage report'; ...       % Structure-based code coverage report              | verifyObjCode2LowLevelTests %
                    'BV SIL results'; ...                 % Boundary value SIL test results                   | verifyObjCode2BoundValTests %
                    'BV SIL report'; ...                  % Boundary value SIL test report                    | verifyObjCode2BoundValTests %
                    'BV PIL results'; ...                 % Boundary value PIL test results                   | verifyObjCode2BoundValTests %
                    'BV PIL report'; ...                  % Boundary value PIL test report                    | verifyObjCode2BoundValTests %
%                     'BV SIL results (instrumented)'; ...  % Boundary value SIL test results (instrumented)    | verifyObjCode2BoundValTests %
%                     'BV SIL report (instrumented)'; ...   % Boundary value SIL test report (instrumented)     | verifyObjCode2BoundValTests %
%                     'BV PIL results (instrumented)'; ...  % Boundary value PIL test results (instrumented)    | verifyObjCode2BoundValTests %
%                     'BV PIL report (instrumented)'; ...   % Boundary value PIL test report (instrumented)     | verifyObjCode2BoundValTests %
                    'BV code coverage'; ...               % Boundary value code coverage results              | verifyObjCode2BoundValTests %
                    'BV code coverage report'; ...        % Boundary value code coverage report               | verifyObjCode2BoundValTests %
                    'code coverage'; ...                  % Cumulative code coverage results                  | mergeCodeCoverage           %
                    'code coverage report'; ...           % Cumulative code coverage report                   | mergeCodeCoverage           %
                    'code standards report'; ...          % Coding rules analysis report                      | checkCodeStds               %
                    'code metrics report'; ...            % Code metrics analysis report                      | computeCodeMetrics          %
                    'bug finder report'; ...              % Bug Finder analysis report                        | detectCodingErrs            %
                    'code prover report'; ...             % Code Prover analysis report                       | proveCodeQuality            %
                    'call hierarchy report'; ...          % Call hierarchy analysis report                    | proveCodeQuality            %
                    'variable access report'; ...         % Variable access analysis report                   | proveCodeQuality            %
                    'code report'; ...                    % Code generation report                            | genSrcCode                  %
                    'model review checklist'; ...         % Model review checklist                            | createChecklist             %
                    'gate review checklist'; ...          % Gate review checklist                             | createChecklist             %
                    'test review checklist'; ...          % Test review checklist                             | createChecklist             %
                    'model advisor configuration'; ...    % Model Advisor configuration                       | checkModelStds              %
                    'model template'};                    % Model template                                    | addModelFolder              %
                                                          %=================================================================================%
        nameVals = {'open_<MODEL>'; ...
                    'DD_<MODEL>'; ...
                    'localDD_<MODEL>'; ...
                    '<MODEL>_Requirements_Report'; ...
                    '<MODEL>_SDD'; ...
                    '<MODEL>_Harness_REQ'; ...
                    '<MODEL>_REQ_Based_Test'; ...
                    '<MODEL>_REQ_Based_Test_Results'; ...
                    '<MODEL>_REQ_Based_Test_Report'; ...
                    '<MODEL>_REQ_Based_Model_Coverage'; ...
                    '<MODEL>_REQ_Based_Model_Coverage_Report'; ...
                    '<MODEL>_Test_Generation_Report'; ...
                    '<MODEL>_Harness_SLDV'; ...
                    '<MODEL>_SLDV_Based_Test'; ...
                    '<MODEL>_SLDV_Based_Test_Results'; ...
                    '<MODEL>_SLDV_Based_Test_Report'; ...
                    '<MODEL>_SLDV_Based_Model_Coverage'; ...
                    '<MODEL>_SLDV_Based_Model_Coverage_Report'; ...
                    '<MODEL>_BV_Test_Generation_Report'; ...
                    '<MODEL>_Harness_BV'; ...
                    '<MODEL>_BV_Based_Test'; ...
                    '<MODEL>_BV_Based_Test_Results'; ...
                    '<MODEL>_BV_Based_Test_Report'; ...
                    '<MODEL>_BV_Based_Model_Coverage'; ...
                    '<MODEL>_BV_Based_Model_Coverage_Report'; ...
                    '<MODEL>_Merged_Model_Coverage'; ...
                    '<MODEL>_Merged_Model_Coverage_Report'; ...
                    '<MODEL>_Model_Advisor_Report'; ...
                    '<MODEL>_Model_Metrics_Report'; ...
                    '<MODEL>_Design_Error_Detection_Results'; ...
                    '<MODEL>_Design_Error_Detection_Report'; ...
                    '<MODEL>_SIL_REQ_Based_Test_Results'; ...
                    '<MODEL>_SIL_REQ_Based_Test_Report'; ...
                    '<MODEL>_PIL_REQ_Based_Test_Results'; ...
                    '<MODEL>_PIL_REQ_Based_Test_Report'; ...
%                     '<MODEL>_INSTR_SIL_REQ_Based_Test_Results'; ...
%                     '<MODEL>_INSTR_SIL_REQ_Based_Test_Report'; ...
%                     '<MODEL>_INSTR_PIL_REQ_Based_Test_Results'; ...
%                     '<MODEL>_INSTR_PIL_REQ_Based_Test_Report'; ...
                    '<MODEL>_REQ_Based_Code_Coverage'; ...
                    '<MODEL>_REQ_Based_Code_Coverage_Report'; ...
                    '<MODEL>_SIL_SLDV_Based_Test_Results'; ...
                    '<MODEL>_SIL_SLDV_Based_Test_Report'; ...
                    '<MODEL>_PIL_SLDV_Based_Test_Results'; ...
                    '<MODEL>_PIL_SLDV_Based_Test_Report'; ...
%                     '<MODEL>_INSTR_SIL_SLDV_Based_Test_Results'; ...
%                     '<MODEL>_INSTR_SIL_SLDV_Based_Test_Report'; ...
%                     '<MODEL>_INSTR_PIL_SLDV_Based_Test_Results'; ...
%                     '<MODEL>_INSTR_PIL_SLDV_Based_Test_Report'; ...
                    '<MODEL>_SLDV_Based_Code_Coverage'; ...
                    '<MODEL>_SLDV_Based_Code_Coverage_Report'; ...
                    '<MODEL>_SIL_BV_Based_Test_Results'; ...
                    '<MODEL>_SIL_BV_Based_Test_Report'; ...
                    '<MODEL>_PIL_BV_Based_Test_Results'; ...
                    '<MODEL>_PIL_BV_Based_Test_Report'; ...
%                     '<MODEL>_INSTR_SIL_BV_Based_Test_Results'; ...
%                     '<MODEL>_INSTR_SIL_BV_Based_Test_Report'; ...
%                     '<MODEL>_INSTR_PIL_BV_Based_Test_Results'; ...
%                     '<MODEL>_INSTR_PIL_BV_Based_Test_Report'; ...
                    '<MODEL>_BV_Based_Code_Coverage'; ...
                    '<MODEL>_BV_Based_Code_Coverage_Report'; ...
                    '<MODEL>_Merged_Code_Coverage'; ...
                    '<MODEL>_Merged_Code_Coverage_Report'; ...
                    '<MODEL>_Code_Standards_Report'; ...
                    '<MODEL>_Code_Metrics_Report'; ...
                    '<MODEL>_Bug_Finder_Report'; ...
                    '<MODEL>_Code_Prover_Report'; ...
                    '<MODEL>_Call_Hierarchy_Report'; ...
                    '<MODEL>_Variable_Access_Report'; ...
                    'index'; ...
                    '<MODEL>_Model_Review_Checklist'; ...
                    '<MODEL>_Gate_Review_Checklist'; ...
                    '<MODEL>_Test_Review_Checklist'; ...
                    'iso26262Checks'; ...
                    'isoModelTemplate'};
        nameMap = containers.Map(prjNameConv.nameKeys, prjNameConv.nameVals);
    end
    
    methods (Static)
        function nameStr = getNameStr(key, varargin)
            if nargin > 1
                nameStr = prjNameConv.nameMap(key);
                nameStr = strrep(nameStr, '<MODEL>', varargin{1});
            else
                nameStr = prjNameConv.nameMap(key);
            end
        end
    end
    
end
